name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Instalacja zależności
        run: pip install -r requirements.txt

      - name: Migracje Django
        run: python manage.py migrate

      - name: Testy Django
        run: python manage.py test